### PR TITLE
fix: #27 - Implement the "protected branches" API endpoint

### PR DESCRIPTION
**Pull request by rbartuzel**
Could you please take a look at my PR?

### CODE REVIEW

**Comment by gdubicki** [comment]
Hi @rbartuzel ! Thank you for the PR!

We are striving to add for all new/fixed features tests for initially configuring, changing and deleting given feature. Can you please add tests for changing branch protection level and for removing protection of a branch?

**Comment by rbartuzel** [comment]
Hi! I have added tests for changing branch protection level and for removing protection of a branch.

**Comment by wadimklincov** [comment]
For me using branch names with wildcards doesn't work, because it still uses the old endpoint for unprotecting branches.

**Comment by gdubicki** [comment]
Thanks @wadimklincov ! 

@rbartuzel : how about we:

1. Make unprotect method call **both** old API (like it does now) and the new one (like @wadimklincov suggested) to ensure that given branch is really unprotected.

2. Make unprotect method calls accept 404 as the return code too (we already do that in a few other places, see https://github.com/egnyte/gitlabform/blob/master/gitlabform/gitlab/members.py#L18 as an example).

3. Add some more tests for unprotecting and protecting:

a) configure protection using old API and switch it to new,
b) the other way around,

?

I think we would have all cases covered then.

**Comment by rbartuzel** [comment]
@gdubicki Sounds like a good idea, I'll try to fix it.

**Comment by rbartuzel** [comment]
Hi!

I noticed that it's not required to call unprotect using both api method. Unprotect method from new api can also unprotect branches protected old way.

I modified one of existing test to cover use case with wildcards, and added new ones to cover use case with set protection using old api and updating with new api and vice versa.

If you have any comments or suggestions, just let me know.

**Comment by wadimklincov** [comment]
Awesome, it works great!

I just have two things I noticed while testing:

* if `protected: false` is set, but the rest of the parameters are still specified, it's still protected
* if the branch is removed from the configuration, it still stays protected

I guess the latter one is difficult to do, though.

**Comment by rbartuzel** [comment]
@wadimklincov thanks for testing!
I fixed first issue but in case of the second, I agree it could be difficult to do.

**Comment by gdubicki** [comment]
LGTM. Thanks for implementation @rbartuzel and for the tests @wadimklincov !

**Pull request merged**
