### PR TITLE
Remove extra approval rules if they are not set via GitlabForm

### PR DESCRIPTION
**Pull request by Pigueiras**

### CODE REVIEW

**Comment by gdubicki** [comment]
Hey @Pigueiras ! Thanks for the contribution.

However it seems to me that this feature should be disabled by default as otherwise it could make some GitLabForm users lose their configs - the manually configured approvals rules. And as they would be manually configured they could be hard to restore... :(

Can you please add a feature flag for this then?

**Comment by Pigueiras** [comment]
@gdubicki I implemented the option + added a test, let me know if you want any other change or if I should change something.

**Comment by Pigueiras** [comment]
When I run the integration tests against my test instance it looks good, not sure if those integration tests are failing specifically because of this PR 😄

**Comment by gdubicki** [comment]
Yeah, the failing tests do not have anything to do with your code, @Pigueiras ... But we have to fix them anyway. Let's do this: I'll merge this PR and release a pre-release of Gitlabform with your feature so you start using it and within a few days, after fixing the tests, we'll make a regular release. :)

**Comment by gdubicki** [comment]
https://pypi.org/project/gitlabform/1.21.0rc2/ is ready, @Pigueiras !

**Comment by Pigueiras** [comment]
Thanks @gdubicki ! I very much appreciate it!

**Comment by trzeciakp** [comment]
@gdubicki Are you going to release that change in a stable release (not RC)? Or is `1.21.0rc2` stable but just a name  is misleading?

I'm looking forward to this change!

**Comment by Pigueiras** [comment]
Are you missing tests from this PR or from other stuff @gdubicki ? I did a test along with the PR but let me know if I can do something else.

**Comment by gdubicki** [comment]
Sorry, I was mistaken, it were not missing tests but broken tests. They are now fixed and I see f.e. in https://github.com/egnyte/gitlabform/runs/2247907138?check_suite_focus=true#step:5:132 that your test is passing. Releasing new final release then. :)

**Pull request merged**
