### PR TITLE
feat: #124 - Add configurable timeout for http calls

### PR DESCRIPTION
**Pull request by grzesuav**

### CODE REVIEW

**Comment by grzesuav** [comment]
@gdubicki I couldn't find any tests for `core.py`, does it have separate test class ?

**Comment by gdubicki** [comment]
Thank you for the PR, @grzesuav ! 👍🤝 There are no tests for core yet. You may add them if you want but I can also merge your PR as it is.

**Comment by grzesuav** [comment]
@gdubicki please merge, I will test on production ;)

**Comment by gdubicki** [comment]
😆

**Comment by gdubicki** [comment]
I will make a release over the weekend, @grzesuav. Have a nice one!

**Comment by grzesuav** [comment]
thanks, same to you @gdubicki !

**Pull request merged**
