### PR TITLE
Update to allow a '0' access for Protected tags - issue #172

### PR DESCRIPTION
**Pull request by mcjffld**
quick change, tested locally, now getting

{"create_access_level": 0, "name": "*"}

### CODE REVIEW

**Comment by gdubicki** [comment]
Thanks @mcjffld , but can you please add a test for this?

**Comment by mcjffld** [comment]
> Thanks @mcjffld , but can you please add a test for this?

I'd love to - I did and some code that runs a test and passes, but I wasn't able to figure out how to actually test that the tag change was working - the get_tags call returned an empty list all the time

any thoughts?

**Comment by gdubicki** [comment]
Sorry for keeping you waiting, @mcjffld .

You have to use `create_tags` to create some tags before protecting them.

**Comment by gdubicki** [comment]
As we are close to release of v2, can you please rebase your MR to it and target that branch, @mcjffld ?

**Comment by gdubicki** [comment]
Hey @mcjffld ! Do you have the time and the will do continue working on this? Because I just added the new style tests for protecting tags into the `main` branch, so it would be much easier for you to just add a new test there instead of adding a whole new set of tests in the `gitlabform.gitlab` package.

**Comment by gdubicki** [comment]
I have fixed it in https://github.com/egnyte/gitlabform/pull/245/commits/2d2e36922ac15c283ca1eb1d770174a63c13ca3c as I don't want bugs in the app to linger for too long.

Thanks for your effort @mcjffld , don't hesitate to take on another bug or feature in future. 😊

**Pull request closed without merging**
