### PR TITLE
fix(schedules #148): Add missing return code handling to delete_pipeline_variable

### PR DESCRIPTION
**Pull request by grzesuav**

### CODE REVIEW

**Comment by grzesuav** [comment]
@gdubicki it should do its job

**Comment by gdubicki** [comment]
It should, but can you add a test for it please? It’s the lack of tests that put us into this little mess. :(

**Comment by grzesuav** [comment]
@gdubicki how to  run test at this PR ? I modified test and removed fix to check if it will fail

**Comment by gdubicki** [comment]
We would have to create a schedule first as another user than root (which is used for running GitLabForm in the tests by default) and then run the test to see if the take ownership API endpoint would work... So we would have to do something new in our tests.

The problem with this is that I am not sure if we can even reproduce the 202 status code as it seems that sometimes GitLab performs operations immediately and returns 200 or 201 but sometimes it needs more time and returns 202 "promising" that it will eventually do the requested operation.

So maybe trying to reproduce it in test is not even worth it.


But after all this fighting with the status code recently I am thinking that perhaps we should make a bigger change and just start accepting all 2xx codes by default for all methods + also 404 for DELETEs..?

**Comment by gdubicki** [comment]
Oh, and your code actually did test in https://travis-ci.com/github/egnyte/gitlabform/builds/207940385 but Travis wants to ~exto~make us pay for testing and building this project in a very unpleasant way:

Screenshot 2020-12-17 at 19 50 25

...and clicking on "Consume..." link gives:

Screenshot 2020-12-17 at 19 58 30

🤷‍♂️

**Comment by grzesuav** [comment]
@gdubicki I can try to add support for all 2xx codes by default, is it the way we want to proceed ?

**Comment by kowpatryk** [comment]
@grzesuav I believe this is something we could consider for adding in the next major version, the soonest. However I would be in favour of narrowing down the scope of this fix - and I assume adding just *202* response code would be sufficient here :)

**Comment by grzesuav** [comment]
@gdubicki @kowpatryk restored to first version then

**Pull request merged**
